-- MySQL Script generated by MySQL Workbench
-- Thu Mar 29 00:02:07 2018
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `mydb` DEFAULT CHARACTER SET utf8 ;
USE `mydb` ;

-- -----------------------------------------------------
-- Table `mydb`.`Customer`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Customer` (
  `CID` INT NOT NULL AUTO_INCREMENT,
  `FN` VARCHAR(45) NULL,
  `LN` VARCHAR(45) NULL,
  `Email` VARCHAR(45) NULL,
  `Password` VARCHAR(45) NULL,
  PRIMARY KEY (`CID`),
  UNIQUE INDEX `CID_UNIQUE` (`CID` ASC))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`CreditCard`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`CreditCard` (
  `CID-CCID` INT NOT NULL AUTO_INCREMENT,
  `CID` INT NULL,
  `CC#` INT NULL,
  `CVS` INT NULL,
  `cDate` INT NULL,
  PRIMARY KEY (`CID-CCID`),
  UNIQUE INDEX `CID-CC#ID_UNIQUE` (`CID-CCID` ASC),
  INDEX `fk_CreditCard_Customer_idx` (`CID` ASC),
  CONSTRAINT `fk_CreditCard_Customer`
    FOREIGN KEY (`CID`)
    REFERENCES `mydb`.`Customer` (`CID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Phone`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Phone` (
  `CID-Phone-ID` INT NULL AUTO_INCREMENT,
  `CID` INT NOT NULL,
  `Phone` DOUBLE NULL,
  UNIQUE INDEX `CID-Phone-ID_UNIQUE` (`CID-Phone-ID` ASC),
  UNIQUE INDEX `CID_UNIQUE` (`CID` ASC),
  CONSTRAINT `fk_Phone_Customer1`
    FOREIGN KEY (`CID-Phone-ID`)
    REFERENCES `mydb`.`Customer` (`CID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Date`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Date` (
  `Order-custID` INT NOT NULL,
  `Date` VARCHAR(45) NULL,
  `CID-CCID` INT NULL,
  PRIMARY KEY (`Order-custID`),
  UNIQUE INDEX `Order-custID_UNIQUE` (`Order-custID` ASC),
  INDEX `fk_Date_CreditCard1_idx` (`CID-CCID` ASC),
  CONSTRAINT `fk_Date_CreditCard1`
    FOREIGN KEY (`CID-CCID`)
    REFERENCES `mydb`.`CreditCard` (`CID-CCID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Sock`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Sock` (
  `SockID` INT NOT NULL AUTO_INCREMENT,
  `Sock_Description` VARCHAR(45) NULL,
  UNIQUE INDEX `Sock_Description_UNIQUE` (`Sock_Description` ASC),
  UNIQUE INDEX `SockID_UNIQUE` (`SockID` ASC))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Charity`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Charity` (
  `CharityID` INT NOT NULL AUTO_INCREMENT,
  `Charity_Description` VARCHAR(45) NULL,
  UNIQUE INDEX `Charity_Description_UNIQUE` (`Charity_Description` ASC),
  UNIQUE INDEX `CharityID_UNIQUE` (`CharityID` ASC))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Order`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Order` (
  `Order-SockID` INT NOT NULL,
  `Order-CustID` INT NULL,
  `SockID` INT NULL,
  `CharityID` INT NULL,
  `Quantity` INT NULL,
  PRIMARY KEY (`Order-SockID`),
  INDEX `fk_Order_Date1_idx` (`Order-CustID` ASC),
  INDEX `fk_Order_Sock1_idx` (`SockID` ASC),
  INDEX `fk_Order_Charity1_idx` (`CharityID` ASC),
  CONSTRAINT `fk_Order_Date1`
    FOREIGN KEY (`Order-CustID`)
    REFERENCES `mydb`.`Date` (`Order-custID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Order_Sock1`
    FOREIGN KEY (`SockID`)
    REFERENCES `mydb`.`Sock` (`SockID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Order_Charity1`
    FOREIGN KEY (`CharityID`)
    REFERENCES `mydb`.`Charity` (`CharityID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Building`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Building` (
  `Building` INT NULL,
  `Room` INT NULL,
  `Order-custID` INT NULL,
  UNIQUE INDEX `Building#_UNIQUE` (`Building` ASC),
  CONSTRAINT `fk_Building_Date1`
    FOREIGN KEY (`Order-custID`)
    REFERENCES `mydb`.`Date` (`Order-custID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
